server:
  port: 8770

eureka:
  #  instance:
  #    hostname: localhost
  client:
    enabled: false
    #    registerWithEureka: false
    #    fetchRegistry: false
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

  application:
    name: netflix-eureka-client



