
#  rabbitmq:
#    host: 127.0.0.1
#    port: 5672
#    virtual-host: /
#    username: guest # 默认的guest用户
#    password: guest
rabbitmq:
    host: 127.0.0.1
    port: 5672    # 端口
    virtual-host: /
    username: test
    password: 123456
server:
    port: 8100